branch-defaults:
  master:
    environment: autotaskvalidation-dev
global:
  application_name: autotaskvalidation
  default_ec2_keyname: autotaskvalidation
  default_platform: 64bit Amazon Linux 2016.03 v2.1.3 running Python 3.4
  default_region: eu-west-1
  profile: eb-cli
  sc: git
