# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-18 00:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autotask_web_app', '0018_auto_20160812_0255'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='atresource_id',
            field=models.CharField(default=1, max_length=254),
            preserve_default=False,
        ),
    ]
