# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-19 00:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('autotask_web_app', '0019_profile_atresource_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='autotask_web_app.Profile'),
            preserve_default=False,
        ),
    ]
