# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-19 01:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autotask_web_app', '0021_auto_20160819_0220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='name',
            field=models.CharField(max_length=254),
        ),
    ]
