# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-19 21:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autotask_web_app', '0024_auto_20160819_2210'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='company_id',
            new_name='company',
        ),
    ]
