# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-19 21:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autotask_web_app', '0025_auto_20160819_2214'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookingindetails',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='upsell',
            name='profile',
        ),
        migrations.DeleteModel(
            name='BookingInDetails',
        ),
        migrations.DeleteModel(
            name='Upsell',
        ),
    ]
