# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-19 21:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autotask_web_app', '0026_auto_20160819_2237'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='company',
        ),
        migrations.AddField(
            model_name='profile',
            name='company_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
