# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-20 00:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('autotask_web_app', '0033_validation_mandatory'),
    ]

    operations = [
        migrations.CreateModel(
            name='ValidationGroupRule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=254)),
                ('operator', models.CharField(max_length=254)),
                ('picklist_number', models.IntegerField()),
                ('value', models.CharField(max_length=254)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autotask_web_app.Entity')),
                ('validation_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autotask_web_app.ValidationGroup')),
            ],
        ),
    ]
